### ISSUE TITLE
怎么加入一番队？

### ISSUE THREAD

**Issue by zhanzengyu** [yifandui/MasteringAndroid#2]
好像是 BLEACH 里面的场景。

楼主不是海贼王的头像吗？

哈哈哈

**Comment by czn6** [comment]
哈哈 你好 ，目前是个秘密哟

**Comment by czn6** [comment]
如果你想加入 可以尝试贡献一点 找个某个专题输出一篇文章 发个 PR 如果被合并了 就会邀请你哟~
